# Generated by Django 5.2.6 on 2025-10-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawelement',
            name='geometry_volume',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geometry의 체적 (cubic units)', max_digits=20, null=True, verbose_name='형상 체적'),
        ),
    ]
