# Generated by Django 5.2.6 on 2025-10-28 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_rawelement_geometry_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawelement',
            name='geometry_volume',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geometry의 체적 (cubic units)', max_digits=20, null=True, verbose_name='Geometry Volume'),
        ),
        migrations.CreateModel(
            name='SplitElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_geometry_volume', models.DecimalField(decimal_places=6, help_text='원본 BIM 객체의 geometry_volume (최초 BIM 원본 기준, 캐시됨)', max_digits=20)),
                ('geometry_volume', models.DecimalField(decimal_places=6, help_text='이 분할 객체의 실제 geometry volume', max_digits=20)),
                ('volume_ratio', models.DecimalField(decimal_places=6, help_text='원본 BIM 대비 체적 비율 (geometry_volume / original_geometry_volume)', max_digits=10)),
                ('split_method', models.CharField(choices=[('plane', 'Plane Split'), ('sketch', 'Sketch Split')], help_text='분할 방식 (plane: 평면 분할, sketch: 스케치 분할)', max_length=20)),
                ('split_axis', models.CharField(blank=True, choices=[('x', 'X Axis'), ('y', 'Y Axis'), ('z', 'Z Axis')], help_text='분할 축 (plane split only: x, y, z)', max_length=1, null=True)),
                ('split_position', models.DecimalField(blank=True, decimal_places=2, help_text='분할 위치 (plane split only: 0-100 백분율)', max_digits=5, null=True)),
                ('split_part_type', models.CharField(choices=[('bottom', 'Bottom Part (Plane Split)'), ('top', 'Top Part (Plane Split)'), ('remainder', 'Remainder Part (Sketch Split)'), ('extracted', 'Extracted Part (Sketch Split)')], help_text='분할 부분 타입 (bottom/top for plane, remainder/extracted for sketch)', max_length=20)),
                ('geometry_data', models.JSONField(default=dict, help_text='3D 뷰 재생성을 위한 geometry 데이터 (vertices, faces, matrix 등)')),
                ('sketch_data', models.JSONField(blank=True, default=dict, help_text='스케치 분할 정보 (스케치 포인트, 평면 법선 등)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태 (BIM 원본이 변경되면 False로 설정)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터 (사용자 메모, 태그 등)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_split', models.ForeignKey(blank=True, help_text='부모 분할 객체 (분할의 분할인 경우)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_splits', to='connections.splitelement')),
                ('project', models.ForeignKey(help_text='프로젝트', on_delete=django.db.models.deletion.CASCADE, related_name='split_elements', to='connections.project')),
                ('raw_element', models.ForeignKey(help_text='원본 BIM 객체 (최초 분할 대상)', on_delete=django.db.models.deletion.CASCADE, related_name='split_elements', to='connections.rawelement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['raw_element', 'is_active'], name='connections_raw_ele_9b5868_idx'), models.Index(fields=['project', 'is_active'], name='connections_project_2c2f92_idx'), models.Index(fields=['parent_split'], name='connections_parent__dca58c_idx')],
            },
        ),
    ]
