# Generated by Django 5.2.6 on 2025-10-28 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_rawelement_geometry_volume_splitelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='활성 상태 (분할된 경우 원본은 False)'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='source_cost_item',
            field=models.ForeignKey(blank=True, help_text='원본 산출항목 (분할 전)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_items', to='connections.costitem'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='split_element',
            field=models.ForeignKey(blank=True, help_text='이 산출항목이 속한 분할 객체', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='connections.splitelement'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='volume_ratio_applied',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='적용된 체적 비율 (quantity = 원본 quantity × volume_ratio)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quantitymember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='활성 상태 (분할된 경우 원본은 False)'),
        ),
        migrations.AddField(
            model_name='quantitymember',
            name='source_quantity_member',
            field=models.ForeignKey(blank=True, help_text='원본 산출부재 (분할 전)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_members', to='connections.quantitymember'),
        ),
        migrations.AddField(
            model_name='quantitymember',
            name='split_element',
            field=models.ForeignKey(blank=True, help_text='이 산출부재가 속한 분할 객체', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity_members', to='connections.splitelement'),
        ),
    ]
