# Generated by Django 5.2.6 on 2025-10-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_costitem_is_active_costitem_source_cost_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcode',
            name='detail_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='내역코드'),
        ),
        migrations.AddField(
            model_name='costcode',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='costcode',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='품명'),
        ),
    ]
