# Generated by Django 5.2.6 on 2025-10-31 03:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_costcode_detail_code_costcode_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='공정코드', max_length=100)),
                ('name', models.CharField(help_text='공정명', max_length=255)),
                ('description', models.TextField(blank=True, help_text='공정 설명', null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='소요일수 (working days)', max_digits=10)),
                ('planned_start_date', models.DateField(blank=True, help_text='계획 시작일', null=True)),
                ('planned_end_date', models.DateField(blank=True, help_text='계획 종료일', null=True)),
                ('actual_start_date', models.DateField(blank=True, help_text='실제 시작일', null=True)),
                ('actual_end_date', models.DateField(blank=True, help_text='실제 종료일', null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='진척률 (0-100%)', max_digits=5)),
                ('status', models.CharField(choices=[('not_started', '미시작'), ('in_progress', '진행중'), ('completed', '완료'), ('on_hold', '보류'), ('cancelled', '취소')], default='not_started', help_text='공정 상태', max_length=20)),
                ('resources', models.JSONField(blank=True, default=dict, help_text='투입 자원 정보 (인력, 장비 등)')),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='예상 비용', max_digits=19)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='실제 비용', max_digits=19)),
                ('wbs_code', models.CharField(blank=True, help_text='WBS 코드 (예: 1.2.3)', max_length=100)),
                ('responsible_person', models.CharField(blank=True, help_text='담당자', max_length=100)),
                ('contractor', models.CharField(blank=True, help_text='시공사/협력업체', max_length=200)),
                ('location', models.CharField(blank=True, help_text='작업 위치', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='비고')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_activity', models.ForeignKey(blank=True, help_text='상위 공정 (WBS 구조)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='connections.activity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='connections.project')),
            ],
            options={
                'ordering': ['wbs_code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='quantitymember',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='이 산출부재에 할당된 공정/액티비티', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_members', to='connections.activity'),
        ),
        migrations.CreateModel(
            name='ActivityDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-to-Start (FS)'), ('SS', 'Start-to-Start (SS)'), ('FF', 'Finish-to-Finish (FF)'), ('SF', 'Start-to-Finish (SF)')], default='FS', help_text='선후행 관계 유형', max_length=2)),
                ('lag_days', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Lag Time (지연 시간, 양수 = 지연, 음수 = 앞당기기/Lead)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='관계 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predecessor_activity', models.ForeignKey(help_text='선행 공정', on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='connections.activity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_dependencies', to='connections.project')),
                ('successor_activity', models.ForeignKey(help_text='후행 공정', on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='connections.activity')),
            ],
            options={
                'ordering': ['predecessor_activity__code', 'successor_activity__code'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', 'status'], name='connections_project_d8781a_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['planned_start_date', 'planned_end_date'], name='connections_planned_85443c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('project', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='activitydependency',
            unique_together={('predecessor_activity', 'successor_activity', 'dependency_type')},
        ),
    ]
