# Generated by Django 5.2.6 on 2025-10-31 04:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_activity_quantitymember_activity_activitydependency_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='connections_project_d8781a_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='connections_planned_85443c_idx',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actual_start_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='planned_end_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='planned_start_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='단위수량당 소요일수 (duration per unit quantity)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', 'code'], name='connections_project_ce8bee_idx'),
        ),
    ]
