# Generated by Django 5.2.6 on 2025-10-31 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_remove_activity_connections_project_d8781a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='이 산출항목에 할당된 액티비티 코드 (실제 액티비티 객체 생성의 기준)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_items', to='connections.activity'),
        ),
    ]
