# Generated by Django 5.2.6 on 2025-10-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_costitem_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costitem',
            name='activity',
        ),
        migrations.AddField(
            model_name='costitem',
            name='activities',
            field=models.ManyToManyField(blank=True, help_text='이 산출항목에 할당된 액티비티 코드들 (복수 할당 가능)', related_name='cost_items', to='connections.activity'),
        ),
    ]
