# Generated by Django 5.2.6 on 2025-10-31 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_remove_costitem_activity_costitem_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_days', models.JSONField(default=dict, help_text="작업 요일 설정 예: {'mon': true, 'tue': true, ..., 'sun': false}")),
                ('holidays', models.JSONField(default=list, help_text="휴일 목록 예: ['2025-01-01', '2025-12-25']")),
                ('special_working_days', models.JSONField(default=list, help_text="특별 작업일 목록 예: ['2025-05-05']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendar', to='connections.project')),
            ],
        ),
    ]
