# Generated by Django 5.2.6 on 2025-10-31 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0010_workcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='work_calendar',
            field=models.ForeignKey(blank=True, help_text='이 액티비티에 적용할 작업 캘린더 (미설정시 프로젝트 기본 캘린더 사용)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='connections.workcalendar'),
        ),
    ]
