# Generated by Django 5.2.6 on 2025-10-31 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0011_activity_work_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workcalendar',
            options={'ordering': ['-is_main', 'name']},
        ),
        migrations.AddField(
            model_name='workcalendar',
            name='is_main',
            field=models.BooleanField(default=False, help_text='메인 캘린더 여부'),
        ),
        migrations.AddField(
            model_name='workcalendar',
            name='name',
            field=models.CharField(default='기본 캘린더', help_text='캘린더 이름', max_length=200),
        ),
        migrations.AlterField(
            model_name='workcalendar',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendars', to='connections.project'),
        ),
        migrations.AlterUniqueTogether(
            name='workcalendar',
            unique_together={('project', 'name')},
        ),
    ]
