# Generated by Django 5.2.6 on 2025-10-31 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0012_alter_workcalendar_options_workcalendar_is_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAssignmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='새 액티비티 할당 규칙', max_length=255)),
                ('description', models.TextField(blank=True, help_text='규칙 설명', null=True)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='규칙이 적용될 CostItem을 필터링하는 조건 (다단계 속성 접근 지원)')),
                ('priority', models.IntegerField(default=0, help_text='우선순위 (낮을수록 먼저 적용)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignment_rules', to='connections.project')),
                ('target_activity', models.ForeignKey(help_text='할당할 액티비티', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='connections.activity')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
