# Generated by Django 5.2.6 on 2025-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0014_classification_assignment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitymember',
            name='locked_properties',
            field=models.JSONField(blank=True, default=list, help_text='룰셋 적용에서 제외할 속성 이름 목록'),
        ),
    ]
