# Generated by Django 5.2.6 on 2025-11-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0015_quantitymember_locked_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitymember',
            name='locked_cost_code_ids',
            field=models.JSONField(blank=True, default=list, help_text='잠금된 공사코드 ID 목록 (UUID strings)'),
        ),
    ]
