# Generated by Django 5.2.6 on 2025-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0016_add_locked_cost_code_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='locked_activity_ids',
            field=models.JSONField(blank=True, default=list, help_text='잠금된 액티비티 ID 목록 (UUID strings)'),
        ),
    ]
