# Generated by Django 5.2.6 on 2025-11-03 06:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0017_costitem_locked_activity_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, help_text='시작일', null=True)),
                ('end_date', models.DateField(blank=True, help_text='종료일', null=True)),
                ('actual_duration', models.DecimalField(blank=True, decimal_places=2, help_text='실제 소요일수 (계산 또는 수동 입력)', max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='수량 (기본값: cost_item.quantity)', max_digits=19)),
                ('is_manual', models.BooleanField(default=False, help_text='수동으로 일자/수량을 입력했는지 여부')),
                ('manual_formula', models.TextField(blank=True, help_text='수동 입력 시 사용한 산식')),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='진행률 (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(help_text='연관된 액티비티 코드', on_delete=django.db.models.deletion.CASCADE, related_name='activity_objects', to='connections.activity')),
                ('cost_item', models.ForeignKey(help_text='연관된 산출항목', on_delete=django.db.models.deletion.CASCADE, related_name='activity_objects', to='connections.costitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_objects', to='connections.project')),
            ],
            options={
                'ordering': ['start_date', 'cost_item'],
                'indexes': [models.Index(fields=['project', 'activity'], name='connections_project_6f941b_idx'), models.Index(fields=['cost_item', 'is_active'], name='connections_cost_it_8ad6a2_idx')],
                'unique_together': {('cost_item', 'activity')},
            },
        ),
    ]
