# Generated by Django 5.2.6 on 2025-11-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0018_create_activity_object_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='is_manual_quantity',
            field=models.BooleanField(default=False, help_text='수동으로 입력된 수량 여부 (True면 자동 생성 시 수량 유지)'),
        ),
    ]
