# Generated by Django 5.2.6 on 2025-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0019_add_is_manual_quantity_to_costitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='manual_start_date',
            field=models.DateField(blank=True, help_text='수동으로 지정한 시작일 (설정 시 의존성 무시하고 이 날짜에 시작)', null=True),
        ),
    ]
