# Generated by Django 5.2.6 on 2025-11-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0020_activity_manual_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costitem',
            name='cost_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='connections.costcode'),
        ),
        migrations.AlterField(
            model_name='unitprice',
            name='unit_price_type',
            field=models.ForeignKey(help_text='단가 구분', on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='connections.unitpricetype'),
        ),
    ]
