# Generated by Django 5.2.6 on 2025-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0021_alter_costitem_cost_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityobject',
            name='quantity_expression',
            field=models.JSONField(blank=True, default=dict, help_text='수동 입력 시 사용한 수량 표현식 (JSON)'),
        ),
    ]
