# Generated by Django 5.2.6 on 2025-11-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0022_activityobject_quantity_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityobject',
            name='quantity_expression',
            field=models.JSONField(blank=True, default=dict, help_text='수동 입력 시 사용한 수량 표현식 (JSON)', null=True),
        ),
    ]
