# Generated by Django 5.2.6 on 2025-11-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0023_alter_activityobject_quantity_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility_filters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
