# Generated by Django 5.2.6 on 2025-11-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0024_project_visibility_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityobject',
            name='cost_item',
            field=models.ForeignKey(blank=True, help_text='연관된 산출항목', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_objects', to='connections.costitem'),
        ),
    ]
