# Generated by Django 5.2.6 on 2025-11-07 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0025_alter_activityobject_cost_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISelectionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ai_selected_ids', models.JSONField(default=list)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('user_corrected_ids', models.JSONField(default=list)),
                ('was_correct', models.BooleanField(default=False)),
                ('false_positives', models.JSONField(default=list)),
                ('false_negatives', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to='connections.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='connections_project_3cf1eb_idx'), models.Index(fields=['was_correct'], name='connections_was_cor_44de9d_idx')],
            },
        ),
    ]
