# Generated by Django 5.2.6 on 2025-11-07 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0026_aiselectionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISelectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('query_pattern', models.CharField(max_length=200)),
                ('category_patterns', models.JSONField(default=list)),
                ('family_patterns', models.JSONField(default=list)),
                ('type_patterns', models.JSONField(default=list)),
                ('parameter_patterns', models.JSONField(default=dict)),
                ('keyword_patterns', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('success_count', models.IntegerField(default=0)),
                ('total_usage', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_rules', to='connections.aiselectionfeedback')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_selection_rules', to='connections.project')),
            ],
            options={
                'ordering': ['-priority', '-confidence', '-created_at'],
                'indexes': [models.Index(fields=['project', 'query_pattern'], name='connections_project_de72bf_idx'), models.Index(fields=['is_active', '-priority'], name='connections_is_acti_c0e482_idx')],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
