# Generated by Django 5.2.6 on 2025-11-07 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0027_aiselectionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_representation', models.TextField()),
                ('embedding_vector', models.JSONField()),
                ('vector_dimension', models.IntegerField(default=768)),
                ('model_name', models.CharField(default='nomic-embed-text', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_embeddings', to='connections.project')),
                ('raw_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='connections.rawelement')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', 'raw_element'], name='connections_project_39ea75_idx')],
                'unique_together': {('raw_element', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='QueryEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=500)),
                ('embedding_vector', models.JSONField()),
                ('vector_dimension', models.IntegerField(default=768)),
                ('model_name', models.CharField(default='nomic-embed-text', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_embeddings', to='connections.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'query_text'], name='connections_project_1eaaf3_idx')],
                'unique_together': {('project', 'query_text', 'model_name')},
            },
        ),
    ]
