# Generated by Django 5.2.6 on 2025-11-07 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0028_objectembedding_queryembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFunctionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(help_text='모델 버전 번호')),
                ('model_type', models.CharField(default='function_classifier', help_text='모델 타입', max_length=50)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_data_count', models.IntegerField(help_text='학습에 사용된 데이터 개수')),
                ('accuracy', models.FloatField(default=0.0, help_text='검증 정확도')),
                ('precision', models.FloatField(default=0.0, help_text='정밀도')),
                ('recall', models.FloatField(default=0.0, help_text='재현율')),
                ('model_data', models.BinaryField(blank=True, help_text='직렬화된 모델 데이터', null=True)),
                ('model_config', models.JSONField(default=dict, help_text='모델 설정 (하이퍼파라미터 등)')),
                ('is_active', models.BooleanField(default=False, help_text='현재 사용 중인 모델')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_function_models', to='connections.project')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIObjectRetrievalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(help_text='모델 버전 번호')),
                ('model_type', models.CharField(default='embedding_retriever', help_text='모델 타입 (embedding_retriever, classifier 등)', max_length=50)),
                ('base_model_name', models.CharField(default='paraphrase-multilingual-MiniLM-L12-v2', help_text='사용된 베이스 임베딩 모델', max_length=200)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_data_count', models.IntegerField(help_text='학습에 사용된 데이터 개수')),
                ('positive_samples', models.IntegerField(default=0, help_text='정답 샘플 개수')),
                ('negative_samples', models.IntegerField(default=0, help_text='오답 샘플 개수')),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('model_path', models.CharField(blank=True, help_text='Fine-tuned 모델 경로 (파일시스템)', max_length=500, null=True)),
                ('model_config', models.JSONField(default=dict, help_text='모델 설정')),
                ('is_active', models.BooleanField(default=False, help_text='현재 사용 중인 모델')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_object_models', to='connections.project')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AISynonymDictionary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_word', models.CharField(help_text='기준이 되는 단어', max_length=100)),
                ('synonyms', models.JSONField(default=list, help_text='유사어 리스트')),
                ('source', models.CharField(default='user', help_text='출처 (user, learned, word2vec 등)', max_length=50)),
                ('usage_count', models.IntegerField(default=0, help_text='사용된 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_synonyms', to='connections.project')),
            ],
            options={
                'ordering': ['canonical_word'],
                'unique_together': {('project', 'canonical_word')},
            },
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='사용자가 입력한 프롬프트')),
                ('function_name', models.CharField(help_text='예측된 함수 이름 (select_objects, calculate_quantity 등)', max_length=100)),
                ('ai_selected_ids', models.JSONField(default=list, help_text='AI가 선택한 객체 ID 리스트')),
                ('correct_ids', models.JSONField(default=list, help_text='사용자가 수정한 정답 객체 ID 리스트')),
                ('false_positive_ids', models.JSONField(default=list, help_text='AI가 잘못 선택한 객체 ID')),
                ('false_negative_ids', models.JSONField(default=list, help_text='AI가 놓친 객체 ID')),
                ('object_features', models.JSONField(default=dict, help_text='각 객체의 features (name, description, classification 등)')),
                ('was_correct', models.BooleanField(default=False, help_text='AI 예측이 정확했는지 여부')),
                ('confidence', models.FloatField(default=0.0, help_text='AI 예측 신뢰도 (0.0~1.0)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('used_for_training', models.BooleanField(default=False, help_text='Fine-tuning에 사용되었는지')),
                ('training_version', models.IntegerField(default=0, help_text='어떤 모델 버전 학습에 사용되었는지')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_training_data', to='connections.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'function_name'], name='connections_project_c4b6a8_idx'), models.Index(fields=['project', 'was_correct'], name='connections_project_1b63c7_idx'), models.Index(fields=['used_for_training'], name='connections_used_fo_cdd508_idx')],
            },
        ),
    ]
