# Generated by Django 5.2.6 on 2025-11-13 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0029_aifunctionmodel_aiobjectretrievalmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryRelationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='룰셋 이름 (예: 기둥-슬라브 관계 분석)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='룰셋 설명', null=True)),
                ('priority', models.IntegerField(default=0, help_text='우선순위 (낮을수록 먼저 실행)')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('target_conditions', models.JSONField(default=dict, help_text='대상 QuantityMember 조건 (기존 조건 빌더 형식)')),
                ('relation_config', models.JSONField(default=dict, help_text='공간 관계 분석 설정')),
                ('property_assignments', models.JSONField(default=dict, help_text='조건부 속성 할당 규칙')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry_relation_rules', to='connections.project')),
            ],
            options={
                'verbose_name': 'Geometry 관계 룰셋',
                'verbose_name_plural': 'Geometry 관계 룰셋',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
