# Generated by Django 5.2.6 on 2025-11-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0030_geometryrelationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcode',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2차품명'),
        ),
        migrations.AddField(
            model_name='costcode',
            name='secondary_spec',
            field=models.TextField(blank=True, null=True, verbose_name='2차규격'),
        ),
        migrations.AddField(
            model_name='costcode',
            name='secondary_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2차단위'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='is_manual_secondary_quantity',
            field=models.BooleanField(default=False, help_text='2차 수량 수동 입력 여부'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='secondary_quantity',
            field=models.FloatField(default=0.0, help_text='2차 수량 (예: 철근 길이)'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='secondary_quantity_mapping_expression',
            field=models.JSONField(blank=True, default=dict, verbose_name='2차 수량 맵핑식(json)'),
        ),
    ]
