# Generated by Django 5.2.6 on 2025-11-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0031_costcode_secondary_name_costcode_secondary_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcode',
            name='secondary_detail_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2차내역코드'),
        ),
    ]
