# Generated by Django 5.2.6 on 2025-11-24 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0032_costcode_secondary_detail_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClassificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='모델 이름 (예: v1.0-catboost)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='모델 설명', null=True)),
                ('version', models.CharField(default='1.0', help_text='모델 버전', max_length=50)),
                ('model_binary', models.BinaryField(help_text='직렬화된 모델 바이너리 (pickle)')),
                ('feature_columns', models.JSONField(default=list, help_text='학습에 사용된 피처 컬럼 리스트')),
                ('label_encoder', models.BinaryField(blank=True, help_text='레이블 인코더 (MultiLabelBinarizer pickle)', null=True)),
                ('training_samples_count', models.IntegerField(default=0, help_text='학습 샘플 수')),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('hyperparameters', models.JSONField(default=dict, help_text='학습 하이퍼파라미터 (iterations, depth, learning_rate, etc.)')),
                ('performance_metrics', models.JSONField(default=dict, help_text="성능 지표: {\n            'hamming_loss': float,\n            'f1_macro': float,\n            'f1_micro': float,\n            'precision_macro': float,\n            'recall_macro': float,\n            'subset_accuracy': float,\n            'per_label_metrics': {label: {f1, precision, recall}},\n            'confusion_matrices': {label: [[tp, fp], [fn, tn]]},\n            'feature_importance': {feature: importance}\n        }")),
                ('is_active', models.BooleanField(default=False, help_text='현재 활성화된 모델인지 (프로젝트당 1개만 활성화)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_classification_models', to='connections.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIClassificationPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_scores', models.JSONField(default=dict, help_text='각 태그별 예측 신뢰도: {tag_id: confidence_score}')),
                ('user_confirmed', models.BooleanField(default=False, help_text='사용자가 예측 결과를 확인/승인했는지')),
                ('feedback_status', models.CharField(choices=[('pending', '확인 대기'), ('accepted', '승인됨'), ('corrected', '수정됨'), ('rejected', '거부됨')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='connections.aiclassificationmodel')),
                ('predicted_tags', models.ManyToManyField(related_name='ai_predicted_samples', to='connections.quantityclassificationtag')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='connections.project')),
                ('raw_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='connections.rawelement')),
                ('user_corrected_tags', models.ManyToManyField(blank=True, help_text='사용자가 수정한 최종 태그들', related_name='user_corrected_samples', to='connections.quantityclassificationtag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIClassificationTrainingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bim_properties', models.JSONField(default=dict, help_text='BIM 속성 스냅샷: {Category, Family, Type, Level, Parameters, etc.}')),
                ('data_source', models.CharField(choices=[('manual', '사용자 수동 할당'), ('ruleset', '룰셋 적용 결과'), ('ai_corrected', 'AI 예측 후 사용자 수정')], default='manual', help_text='데이터 출처', max_length=50)),
                ('is_validated', models.BooleanField(default=False, help_text='사용자가 검증한 고품질 데이터인지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_tags', models.ManyToManyField(help_text='할당된 수량산출 분류 태그들 (다중 레이블 가능)', related_name='training_samples', to='connections.quantityclassificationtag')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_classification_training_data', to='connections.project')),
                ('raw_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_training_records', to='connections.rawelement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiclassificationmodel',
            index=models.Index(fields=['project', 'is_active'], name='connections_project_207bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='aiclassificationprediction',
            index=models.Index(fields=['project', 'feedback_status'], name='connections_project_056500_idx'),
        ),
        migrations.AddIndex(
            model_name='aiclassificationprediction',
            index=models.Index(fields=['project', 'user_confirmed'], name='connections_project_c7acc1_idx'),
        ),
        migrations.AddIndex(
            model_name='aiclassificationtrainingdata',
            index=models.Index(fields=['project', 'is_validated'], name='connections_project_6e4c26_idx'),
        ),
        migrations.AddIndex(
            model_name='aiclassificationtrainingdata',
            index=models.Index(fields=['project', 'data_source'], name='connections_project_cecb49_idx'),
        ),
    ]
