# Generated by Django 5.2.6 on 2025-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0033_aiclassificationmodel_aiclassificationprediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcode',
            name='ai_sd_enabled',
            field=models.BooleanField(default=True, verbose_name='개산견적(SD) 사용'),
        ),
        migrations.AlterField(
            model_name='costcode',
            name='dd_enabled',
            field=models.BooleanField(default=True, verbose_name='상세견적(DD) 사용'),
        ),
    ]
